// ─── CHALLENGE DATA ───────────────────────────────────────────────────────────
// Para agregar un video: completá el campo `video` con la URL (YouTube, etc.)
const CHALLENGES = [
  // ── FÁCIL 1min ──
  {id:'respiracion',name:'Respiración Activa',duration:60,difficulty:'facil',emoji:'💨',
   grad:'linear-gradient(270deg,#001a20,#001018,#001a20)',anim:'breath',video:'',
   desc:'Técnica de respiración diafragmática para reducir el estrés, mejorar el foco y recargar energía mental.',
   steps:['Sentate cómodo, espalda recta','Inhalá por la nariz 4 segundos','Retené el aire 2 segundos','Exhalá lento por la boca 6 seg']},
  {id:'cuello',name:'Rotación de Cuello',duration:60,difficulty:'facil',emoji:'🤸',
   grad:'linear-gradient(270deg,#001020,#000a18,#001020)',anim:'stretch',video:'',
   desc:'Ejercicio suave para liberar la tensión acumulada en el cuello y los hombros durante el día.',
   steps:['Sentate erguido, hombros relajados','Girá la cabeza lentamente a la derecha','Mantenés 3 seg, luego al otro lado','Repetí 5 veces por lado']},
  {id:'munecas',name:'Estiramiento de Muñecas',duration:60,difficulty:'facil',emoji:'✋',
   grad:'linear-gradient(270deg,#0a001a,#000a18,#0a001a)',anim:'stretch',video:'',
   desc:'Aliviá la tensión del teclado con estos estiramientos esenciales para tus muñecas y antebrazos.',
   steps:['Extendé un brazo hacia adelante','Doblá la mano hacia abajo con la otra','Mantenés 15 seg por lado','Cerrá y abrí el puño 10 veces']},
  {id:'hombros',name:'Roll de Hombros',duration:60,difficulty:'facil',emoji:'🤷',
   grad:'linear-gradient(270deg,#001a10,#000a10,#001a10)',anim:'stretch',video:'',
   desc:'Rotaciones suaves para desbloquear los hombros y mejorar la postura después de horas sentado.',
   steps:['Sentate con espalda recta','Subí los hombros hacia las orejas','Rotá hacia atrás en círculos grandes','Hacé 10 círculos adelante y 10 atrás']},
  {id:'pantorrillas',name:'Estiramiento de Pantorrillas',duration:60,difficulty:'facil',emoji:'🦵',
   grad:'linear-gradient(270deg,#001510,#000a10,#001510)',anim:'stretch',video:'',
   desc:'Aliviá la tensión de las pantorrillas acumulada por estar sentado o de pie durante horas.',
   steps:['Parate frente a una pared','Apoyá las manos y extendé una pierna atrás','Talón en el suelo, sentirás el estiramiento','Mantenés 20 seg por lado']},
  {id:'apertura_pecho',name:'Apertura de Pecho',duration:60,difficulty:'facil',emoji:'🤲',
   grad:'linear-gradient(270deg,#001a15,#00100f,#001a15)',anim:'stretch',video:'',
   desc:'Contrarresta la postura encorvada del escritorio abriendo el pecho y activando los músculos posturales.',
   steps:['Parate o sentate erguido','Entrelazá los dedos detrás de la espalda','Apretá los omóplatos y abrí el pecho','Mantenés 15 seg, respirá profundo']},
  {id:'cadera_sentado',name:'Estiramiento de Cadera',duration:60,difficulty:'facil',emoji:'🧘',
   grad:'linear-gradient(270deg,#0a0015,#000510,#0a0015)',anim:'stretch',video:'',
   desc:'Liberá la tensión del flexor de cadera, el músculo más tenso en personas que trabajan sentadas.',
   steps:['Sentate al borde de la silla','Cruzá un tobillo sobre la rodilla opuesta','Inclinate levemente hacia adelante','Mantenés 20 seg por lado']},
  {id:'descanso_visual',name:'Descanso Visual',duration:60,difficulty:'facil',emoji:'👁️',
   grad:'linear-gradient(270deg,#000a1a,#000518,#000a1a)',anim:'breath',video:'',
   desc:'Técnica 20-20-20 para reducir la fatiga ocular causada por pantallas. Tu vista te lo agradecerá.',
   steps:['Cerrá los ojos 10 segundos','Mirá un punto lejano (6m+) por 20 seg','Parpadeá conscientemente 10 veces','Palmeá los ojos suavemente con las manos']},
  {id:'torso_lateral',name:'Estiramiento Lateral',duration:60,difficulty:'facil',emoji:'🙆',
   grad:'linear-gradient(270deg,#001a0a,#000a05,#001a0a)',anim:'stretch',video:'',
   desc:'Estirá los músculos laterales del torso para mejorar la postura y aliviar tensión intercostal.',
   steps:['Sentate o parate con espalda recta','Levantá un brazo y doblate hacia el lado','Sentirás el estiramiento en el costado','Mantenés 15 seg por lado']},
  {id:'movilidad_pies',name:'Movilidad de Pies',duration:60,difficulty:'facil',emoji:'🦶',
   grad:'linear-gradient(270deg,#001015,#000a0f,#001015)',anim:'stretch',video:'',
   desc:'Activá la circulación y la movilidad de tobillos y pies, zonas olvidadas del cuerpo sedentario.',
   steps:['Sentate con un pie levantado','Rotá el tobillo 10 veces por lado','Flexioná y extendé los dedos 10 veces','Masajeá la planta del pie con el pulgar']},
  // ── FÁCIL 3min ──
  {id:'marcha',name:'Marcha en el Lugar',duration:180,difficulty:'facil',emoji:'🚶',
   grad:'linear-gradient(270deg,#002010,#001a0a,#002010)',anim:'squat',video:'',
   desc:'Activá la circulación con esta marcha de bajo impacto, perfecta para hacer en cualquier espacio pequeño.',
   steps:['Parate con pies juntos','Comenzá a marchar elevando rodillas','Coordina con movimiento de brazos','Mantenés ritmo constante 3 minutos']},
  {id:'espalda_baja',name:'Espalda Sin Tensión',duration:180,difficulty:'facil',emoji:'🧘',
   grad:'linear-gradient(270deg,#000a20,#00101a,#000a20)',anim:'stretch',video:'',
   desc:'Secuencia de estiramientos para aliviar el dolor lumbar y mejorar la flexibilidad de la espalda baja.',
   steps:['Acostado boca arriba, rodillas flexionadas','Llevá ambas rodillas al pecho','Mantenés 30 seg, respirando profundo','Hacé rotaciones suaves de cadera']},
  {id:'movilidad',name:'Movilidad Articular',duration:180,difficulty:'facil',emoji:'🔄',
   grad:'linear-gradient(270deg,#0a0a00,#0a1500,#0a0a00)',anim:'circuit',video:'',
   desc:'Rutina de movilización para todas las articulaciones principales. Ideal para comenzar o terminar el día.',
   steps:['Rotá tobillos 10 veces cada uno','Círculos de rodillas 10 veces','Rotá caderas ampliamente','Finalizá con círculos de hombros y cuello']},
  {id:'isquiotibiales',name:'Isquiotibiales Suaves',duration:180,difficulty:'facil',emoji:'🦵',
   grad:'linear-gradient(270deg,#001520,#000f18,#001520)',anim:'stretch',video:'',
   desc:'Estiramiento progresivo de la cadena posterior para aliviar tensión lumbar y mejorar la flexibilidad.',
   steps:['Sentate al borde de la silla','Extendé una pierna con el talón en el piso','Inclinate despacio hacia adelante','1 min por pierna + 1 min ambas juntas']},
  {id:'columna_movil',name:'Movilidad de Columna',duration:180,difficulty:'facil',emoji:'🌀',
   grad:'linear-gradient(270deg,#001018,#000a12,#001018)',anim:'stretch',video:'',
   desc:'Ejercicios de movilización segmental de la columna para descomprimir discos y mejorar la postura.',
   steps:['1 min: Cat-Cow (espalda arqueada y redondeada)','30 seg: Rotaciones de torso sentado','30 seg: Inclinaciones laterales suaves','1 min: Estiramiento de columna en extensión']},
  {id:'meditacion_mov',name:'Meditación en Movimiento',duration:180,difficulty:'facil',emoji:'🌊',
   grad:'linear-gradient(270deg,#00101a,#000a14,#00101a)',anim:'breath',video:'',
   desc:'Combiná respiración consciente con movimientos lentos para reducir el cortisol y centrar la mente.',
   steps:['1 min: Respiración abdominal profunda','30 seg: Movimientos lentos de brazos al inhalar','30 seg: Movimientos lentos de brazos al exhalar','1 min: Quietud consciente con ojos cerrados']},
  {id:'cadera_flex',name:'Flexibilidad de Cadera',duration:180,difficulty:'facil',emoji:'🤸',
   grad:'linear-gradient(270deg,#0a0510,#05010a,#0a0510)',anim:'stretch',video:'',
   desc:'Trabaja la movilidad de cadera para contrarrestar el acortamiento muscular del sedentarismo prolongado.',
   steps:['1 min: Estiramiento de flexor de cadera (media luna)','1 min: Paloma modificada en silla','1 min: Apertura de cadera con rodillas al piso']},
  {id:'caminata_activa',name:'Caminata Activa',duration:180,difficulty:'facil',emoji:'🚶',
   grad:'linear-gradient(270deg,#002015,#001a0f,#002015)',anim:'squat',video:'',
   desc:'Marcha consciente con técnica correcta para activar la circulación y el sistema linfático.',
   steps:['Caminá en el lugar con postura erecta','Elevá las rodillas a 90° con cada paso','Balanceá los brazos de forma coordinada','Aumentá el ritmo gradualmente cada minuto']},
  {id:'espalda_total',name:'Espalda Completa',duration:180,difficulty:'facil',emoji:'🧘',
   grad:'linear-gradient(270deg,#000a20,#00051a,#000a20)',anim:'stretch',video:'',
   desc:'Rutina completa para toda la espalda: cervical, torácica y lumbar. Alivia el dolor del trabajo de escritorio.',
   steps:['1 min: Estiramiento de cuello y cervicales','1 min: Rotación y apertura torácica','1 min: Estiramiento de espalda baja y glúteos']},
  {id:'postura_reset',name:'Reset de Postura',duration:180,difficulty:'facil',emoji:'🧍',
   grad:'linear-gradient(270deg,#001510,#000f0a,#001510)',anim:'stretch',video:'',
   desc:'Secuencia específica para corregir la postura de oficina: cabeza adelantada, hombros caídos y espalda encorvada.',
   steps:['1 min: Chin tucks (retracción cervical)','1 min: Retracción escapular con banda imaginaria','1 min: Pared como espejo (talones, glúteos, hombros, nuca)']},
  // ── FÁCIL 5min ──
  {id:'yoga_desk',name:'Yoga de Escritorio',duration:300,difficulty:'facil',emoji:'🧘',
   grad:'linear-gradient(270deg,#001520,#000a18,#001520)',anim:'stretch',video:'',
   desc:'Secuencia de yoga adaptada para hacer desde tu silla. Alivia tensión y mejora la concentración.',
   steps:['1 min: Estiramiento de cuello y hombros','1 min: Torsión de torso sentado','1 min: Flexión hacia adelante','1 min: Apertura de pecho','1 min: Respiración consciente final']},
  {id:'despertar',name:'Despertar Activo',duration:300,difficulty:'facil',emoji:'☀️',
   grad:'linear-gradient(270deg,#0a1500,#001a0a,#0a1500)',anim:'stretch',video:'',
   desc:'Rutina matutina de 5 minutos para activar el cuerpo suavemente y empezar el día con energía.',
   steps:['1 min: Estiramiento en cama','1 min: Rotación de cuello y hombros','1 min: Marcha suave en el lugar','1 min: Sentadillas lentas','1 min: Respiración de cierre']},
  {id:'relajacion',name:'Relajación Consciente',duration:300,difficulty:'facil',emoji:'😮',
   grad:'linear-gradient(270deg,#000a20,#001015,#000a20)',anim:'breath',video:'',
   desc:'Sesión de relajación guiada para liberar el estrés acumulado y restaurar tu energía mental y física.',
   steps:['1 min: Respiración 4-7-8','1 min: Relajación facial','1 min: Relajación de hombros y manos','1 min: Visualización positiva','1 min: Respiración de retorno']},
  {id:'flexibilidad_total',name:'Flexibilidad Total',duration:300,difficulty:'facil',emoji:'🤸',
   grad:'linear-gradient(270deg,#001520,#000a18,#001520)',anim:'stretch',video:'',
   desc:'Rutina de estiramiento de cuerpo completo para mejorar el rango de movimiento de todas las articulaciones.',
   steps:['1 min: Cuello y hombros','1 min: Torso y columna','1 min: Caderas y glúteos','1 min: Piernas y pantorrillas','1 min: Tobillos y pies']},
  {id:'yoga_suave',name:'Yoga Suave',duration:300,difficulty:'facil',emoji:'🧘',
   grad:'linear-gradient(270deg,#0a001a,#050015,#0a001a)',anim:'stretch',video:'',
   desc:'Secuencia de posturas de yoga restaurativo para calmar el sistema nervioso y liberar tensión profunda.',
   steps:['1 min: Postura del niño (Balasana)','1 min: Gato-Vaca (Cat-Cow)','1 min: Perro boca abajo (Adho Mukha)','1 min: Guerrero 1 (30s c/lado)','1 min: Savasana con respiración']},
  {id:'rutina_postura',name:'Rutina de Postura',duration:300,difficulty:'facil',emoji:'🧍',
   grad:'linear-gradient(270deg,#001a10,#000f0a,#001a10)',anim:'stretch',video:'',
   desc:'Programa completo para corregir y mantener una postura saludable durante toda la jornada.',
   steps:['1 min: Activación de glúteos (clave postural)','1 min: Fortalecimiento de core bajo','1 min: Apertura de pecho y hombros','1 min: Estiramiento cervical completo','1 min: Alineación final de pie contra la pared']},
  {id:'recuperacion_activa',name:'Recuperación Activa',duration:300,difficulty:'facil',emoji:'💆',
   grad:'linear-gradient(270deg,#00101a,#00081a,#00101a)',anim:'breath',video:'',
   desc:'Rutina de recuperación para usar después de otro reto o al final del día. Restaura el cuerpo con calma.',
   steps:['1 min: Respiración diafragmática profunda','1 min: Sacudida suave de brazos y piernas','1 min: Rodamiento de columna (de pie)','1 min: Estiramiento de cadena posterior','1 min: Relajación total en el suelo']},
  {id:'estiramientos_oficina',name:'Estiramientos de Oficina',duration:300,difficulty:'facil',emoji:'💼',
   grad:'linear-gradient(270deg,#001018,#000810,#001018)',anim:'stretch',video:'',
   desc:'Rutina diseñada para hacerse 100% en la silla o de pie sin salir de tu espacio de trabajo.',
   steps:['1 min: Cuello y trapecios (sentado)','1 min: Muñecas y antebrazos','1 min: Espalda alta y hombros (sentado)','1 min: Cadera y glúteos (sentado)','1 min: Pantorrillas y tobillos']},
  {id:'mindfulness_mov',name:'Mindfulness en Movimiento',duration:300,difficulty:'facil',emoji:'🌿',
   grad:'linear-gradient(270deg,#001a05,#000f03,#001a05)',anim:'breath',video:'',
   desc:'Práctica de movimiento consciente inspirada en el Tai Chi para conectar cuerpo y mente en 5 minutos.',
   steps:['1 min: Respiración y centrado','1 min: Movimientos lentos de brazos (flujo)','1 min: Desplazamientos suaves del peso','1 min: Rotaciones lentas de todo el cuerpo','1 min: Quietud y escáner corporal']},
  {id:'cadenas_musculares',name:'Cadenas Musculares',duration:300,difficulty:'facil',emoji:'🔗',
   grad:'linear-gradient(270deg,#001a18,#000f12,#001a18)',anim:'stretch',video:'',
   desc:'Trabaja las cadenas musculares completas (anterior y posterior) para un cuerpo equilibrado y sin tensiones.',
   steps:['1 min: Cadena posterior (espalda a talones)','1 min: Cadena anterior (cuádriceps a pecho)','1 min: Cadena lateral (costado completo)','1 min: Cadena espiral (diagonal)','1 min: Integración con respiración']},
  // ── MEDIO 1min ──
  {id:'plancha',name:'Plancha de Poder',duration:60,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0d2a00,#001a14,#002010,#0d2a00)',anim:'plank',video:'',
   desc:'Mantené la posición de plancha. Activá el core, respirá profundo. Podés hacerlo en cualquier lugar.',
   steps:['Apoyá los antebrazos en el suelo','Cuerpo recto como una tabla','Contraé el abdomen fuerte','Respirá profundo y constante']},
  {id:'sentadillas',name:'Sentadillas Express',duration:60,difficulty:'medio',emoji:'🏋',
   grad:'linear-gradient(270deg,#001020,#0a0020,#001030,#001020)',anim:'squat',video:'',
   desc:'Sentadillas básicas para activar piernas y glúteos. Perfectas entre reuniones o en cualquier pausa.',
   steps:['Pies al ancho de los hombros','Bajá como si fueras a sentarte','Rodillas detrás de los pies','Subí empujando los talones']},
  {id:'jumping',name:'Jumping Jacks',duration:60,difficulty:'medio',emoji:'⚡',
   grad:'linear-gradient(270deg,#001a20,#001020,#001a20)',anim:'circuit',video:'',
   desc:'El clásico ejercicio de saltos para elevar el ritmo cardíaco y activar todo el cuerpo en un minuto.',
   steps:['Parate con pies juntos y brazos abajo','Saltá abriendo pies y llevá brazos arriba','Saltá de regreso a la posición inicial','Mantenés ritmo constante 60 segundos']},
  {id:'puente',name:'Puente de Glúteos',duration:60,difficulty:'medio',emoji:'🦵',
   grad:'linear-gradient(270deg,#0a0010,#001010,#0a0010)',anim:'plank',video:'',
   desc:'Fortalecé glúteos y espalda baja con este ejercicio efectivo que podés hacer en el suelo.',
   steps:['Acostado boca arriba, rodillas flexionadas','Pies apoyados en el suelo, ancho de cadera','Elevá la cadera contrayendo los glúteos','Mantenés 2 seg arriba, bajá despacio']},
  {id:'triceps_silla',name:'Tríceps en Silla',duration:60,difficulty:'medio',emoji:'💺',
   grad:'linear-gradient(270deg,#001525,#000f1a,#001525)',anim:'plank',video:'',
   desc:'Ejercicio de tríceps usando solo tu silla. Tonificá la parte posterior del brazo sin equipamiento.',
   steps:['Sentate al borde de la silla','Apoyá las manos en el borde, dedos hacia adelante','Bajá el cuerpo doblando los codos a 90°','Subí extendiendo los brazos, repetí']},
  {id:'rodillas_altas',name:'Rodillas Altas',duration:60,difficulty:'medio',emoji:'🏃',
   grad:'linear-gradient(270deg,#002018,#001a12,#002018)',anim:'squat',video:'',
   desc:'Marcha explosiva elevando las rodillas para activar el cardio y los flexores de cadera rápidamente.',
   steps:['Parate con pies juntos','Comenzá a correr en el lugar','Elevá cada rodilla hasta la altura de la cadera','Mantené velocidad máxima todo el minuto']},
  {id:'sentadilla_iso',name:'Sentadilla Isométrica',duration:60,difficulty:'medio',emoji:'🏋',
   grad:'linear-gradient(270deg,#001520,#000f18,#001520)',anim:'squat',video:'',
   desc:'Bajá y quedate. La sentadilla estática es uno de los ejercicios más efectivos para piernas y resistencia.',
   steps:['Bajá a posición de sentadilla (muslos paralelos)','Espalda contra la pared si necesario','Mantené la posición sin moverse','Si podés, aguantá todo el minuto']},
  {id:'step_lateral',name:'Step Lateral',duration:60,difficulty:'medio',emoji:'↔️',
   grad:'linear-gradient(270deg,#002015,#001a10,#002015)',anim:'circuit',video:'',
   desc:'Pasos laterales rápidos para activar los abductores, mejorar la agilidad y elevar el ritmo cardíaco.',
   steps:['Parate con pies juntos, rodillas ligeramente flexionadas','Dá 3 pasos rápidos hacia la derecha','Luego 3 pasos hacia la izquierda','Mantené el ritmo constante y los brazos activos']},
  {id:'estocadas',name:'Estocadas Alternas',duration:60,difficulty:'medio',emoji:'🦵',
   grad:'linear-gradient(270deg,#001020,#000a18,#001020)',anim:'squat',video:'',
   desc:'Zancadas alternadas para trabajar piernas, glúteos y el equilibrio de forma dinámica.',
   steps:['Parate erguido con pies juntos','Dá un gran paso adelante con la pierna derecha','Bajá hasta que ambas rodillas formen 90°','Alternás con la izquierda, repetí rítmicamente']},
  {id:'abs_silla',name:'Abdominales en Silla',duration:60,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0d1a00,#081200,#0d1a00)',anim:'plank',video:'',
   desc:'Trabaja el core sentado en tu silla, ideal para hacer en la oficina de forma discreta y efectiva.',
   steps:['Sentate erguido al borde de la silla','Apoyá las manos en los laterales','Levantá ambas rodillas hacia el pecho','Bajá sin tocar el suelo, repetí rítmicamente']},
  // ── MEDIO 3min ──
  {id:'abs_basico',name:'Rutina de Abdomen',duration:180,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0d2000,#002010,#0d2000)',anim:'plank',video:'',
   desc:'Circuito básico de abdominales para fortalecer el core sin equipamiento. Efectivo y directo.',
   steps:['1 min: Abdominales básicos','30 seg: Plancha frontal','30 seg: Elevaciones de piernas','30 seg: Bicicleta abdominal']},
  {id:'piernas',name:'Activación de Piernas',duration:180,difficulty:'medio',emoji:'🦵',
   grad:'linear-gradient(270deg,#001020,#0a0025,#001020)',anim:'squat',video:'',
   desc:'Ejercicios para piernas y glúteos que podés hacer sin moverse del lugar. Sentirás el quemado.',
   steps:['1 min: Sentadillas controladas','30 seg: Zancadas alternadas','30 seg: Elevaciones de talones','30 seg: Sentadilla isométrica (aguantá)']},
  {id:'cardio_suave',name:'Cardio Suave',duration:180,difficulty:'medio',emoji:'🏃',
   grad:'linear-gradient(270deg,#002020,#001020,#002020)',anim:'circuit',video:'',
   desc:'Rutina cardiovascular de bajo impacto para elevar el ritmo cardíaco sin saltar. Ideal para oficina.',
   steps:['1 min: Marcha rápida en el lugar','30 seg: Patadas traseras alternadas','30 seg: Pasos laterales rápidos','30 seg: Boxeo suave (sombra)']},
  {id:'circuito_brazos',name:'Circuito de Brazos',duration:180,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0a1a00,#061200,#0a1a00)',anim:'plank',video:'',
   desc:'Circuito para trabajar bíceps, tríceps y hombros usando solo el peso corporal.',
   steps:['1 min: Flexiones (o contra la pared)','30 seg: Tríceps en silla','30 seg: Círculos de brazos con tensión','30 seg: Press imaginario (isométrico contra marco)']},
  {id:'equilibrio_basico',name:'Trabajo de Equilibrio',duration:180,difficulty:'medio',emoji:'⚖️',
   grad:'linear-gradient(270deg,#001820,#001018,#001820)',anim:'stretch',video:'',
   desc:'Ejercicios de equilibrio para activar los músculos estabilizadores y mejorar la coordinación.',
   steps:['1 min: Equilibrio en un pie (30s c/lado)','1 min: Sentadilla en un pie (asistida)','1 min: Marcha con ojos cerrados (en el lugar)']},
  {id:'cardio_sin_salto',name:'Cardio Sin Salto',duration:180,difficulty:'medio',emoji:'🏃',
   grad:'linear-gradient(270deg,#002018,#001812,#002018)',anim:'circuit',video:'',
   desc:'Rutina cardiovascular de impacto cero: ideal para departamentos, oficinas o madrugadas sin ruido.',
   steps:['1 min: Marcha rápida con brazos activos','30 seg: Sentadillas lentas y controladas','30 seg: Step lateral dinámico','30 seg: Estocadas lentas alternadas']},
  {id:'core_dinamico',name:'Core Dinámico',duration:180,difficulty:'medio',emoji:'🏋',
   grad:'linear-gradient(270deg,#0a1500,#061000,#0a1500)',anim:'plank',video:'',
   desc:'Trabaja el core de forma dinámica con ejercicios que combinan estabilidad y movimiento funcional.',
   steps:['1 min: Dead bug (espalda en el suelo, brazos y piernas)','1 min: Plancha con toque de hombros','1 min: Puente con elevación de un pie']},
  {id:'yoga_dinamico',name:'Yoga Dinámico',duration:180,difficulty:'medio',emoji:'🧘',
   grad:'linear-gradient(270deg,#0a0020,#050018,#0a0020)',anim:'stretch',video:'',
   desc:'Secuencia de yoga con transiciones fluidas para combinar fuerza, flexibilidad y equilibrio.',
   steps:['1 min: Saludo al sol simplificado','1 min: Guerrero 2 fluido (30s c/lado)','1 min: Triángulo y estiramiento lateral']},
  {id:'piernas_fuego',name:'Piernas en Fuego',duration:180,difficulty:'medio',emoji:'🔥',
   grad:'linear-gradient(270deg,#200a00,#180800,#200a00)',anim:'squat',video:'',
   desc:'Circuito intenso de piernas y glúteos para cuando querés sentir el quemado muscular en 3 minutos.',
   steps:['1 min: Sentadillas con pausa de 2 seg abajo','30 seg: Sentadilla plie (pies abiertos)','30 seg: Elevaciones de talones','30 seg: Glúteo en cuadrupedia (30s c/lado)']},
  {id:'funcional_medio',name:'Movimiento Funcional',duration:180,difficulty:'medio',emoji:'🔄',
   grad:'linear-gradient(270deg,#001a20,#001018,#001a20)',anim:'circuit',video:'',
   desc:'Ejercicios que imitan movimientos de la vida real para mejorar la fuerza funcional cotidiana.',
   steps:['1 min: Levantarse y sentarse (sentadilla funcional)','1 min: Empuje y jale de brazos (mimando movimiento)','1 min: Rotaciones de torso con resistencia imaginaria']},
  // ── MEDIO 5min ──
  {id:'hiit_lite',name:'HIIT Suave',duration:300,difficulty:'medio',emoji:'⚡',
   grad:'linear-gradient(270deg,#002010,#001a20,#002010)',anim:'circuit',video:'',
   desc:'Intervalos de alta intensidad adaptados para todos los niveles. 5 minutos de quema efectiva.',
   steps:['1 min: Calentamiento (marcha)','1 min: Sentadillas rápidas','1 min: Saltos suaves','1 min: Plancha con pausa','1 min: Vuelta a la calma']},
  {id:'tren_sup',name:'Tren Superior',duration:300,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0a1500,#001020,#0a1500)',anim:'plank',video:'',
   desc:'Rutina completa para brazos, hombros y espalda. Sin pesas ni equipamiento necesario.',
   steps:['1 min: Flexiones (modificadas ok)','1 min: Tríceps en silla','1 min: Apertura de brazos','1 min: Superman (espalda)','1 min: Estiramiento final']},
  {id:'core_total',name:'Core Total',duration:300,difficulty:'medio',emoji:'🏋',
   grad:'linear-gradient(270deg,#001a10,#00100a,#001a10)',anim:'plank',video:'',
   desc:'Circuito integral para fortalecer todo el núcleo corporal: abdomen, espalda y estabilizadores.',
   steps:['1 min: Plancha frontal','1 min: Plancha lateral (30s c/lado)','1 min: Abdominales lentos','1 min: Bird-dog alternado','1 min: Puente de glúteos final']},
  {id:'fullbody_peso',name:'Full Body Sin Peso',duration:300,difficulty:'medio',emoji:'🏋',
   grad:'linear-gradient(270deg,#001a15,#001010,#001a15)',anim:'circuit',video:'',
   desc:'Circuito de cuerpo completo usando solo el peso corporal. Trabajo de fuerza de pies a cabeza.',
   steps:['1 min: Sentadillas','1 min: Flexiones (modificadas ok)','1 min: Puente de glúteos','1 min: Plancha','1 min: Estiramiento final']},
  {id:'yoga_flow',name:'Yoga Flow',duration:300,difficulty:'medio',emoji:'🌊',
   grad:'linear-gradient(270deg,#000a20,#00051a,#000a20)',anim:'stretch',video:'',
   desc:'Secuencia de yoga con fluidez y transiciones conectadas por la respiración. Fuerza + calma.',
   steps:['1 min: Saludo al sol (x3)','1 min: Serie de guerreros','1 min: Posturas de equilibrio','1 min: Torsiones y estiramientos','1 min: Savasana activo']},
  {id:'resistencia_musc',name:'Resistencia Muscular',duration:300,difficulty:'medio',emoji:'💪',
   grad:'linear-gradient(270deg,#0d2000,#081800,#0d2000)',anim:'plank',video:'',
   desc:'Altas repeticiones y bajo descanso para desarrollar resistencia muscular y resistencia cardio.',
   steps:['1 min: 20 sentadillas + 10 flexiones','1 min: 15 estocadas + 10 abdominales','1 min: 20 puentes + 15 elevaciones de pierna','1 min: 30 jumping jacks','1 min: Estiramiento completo']},
  {id:'tren_inferior',name:'Tren Inferior',duration:300,difficulty:'medio',emoji:'🦵',
   grad:'linear-gradient(270deg,#001525,#000f1a,#001525)',anim:'squat',video:'',
   desc:'Rutina completa de piernas y glúteos en 5 minutos. El tren inferior es el motor del cuerpo.',
   steps:['1 min: Sentadillas sumo','1 min: Estocadas alternadas','1 min: Glúteo en cuadrupedia','1 min: Sentadilla isométrica','1 min: Estiramiento de piernas']},
  {id:'circuito_func',name:'Circuito Funcional',duration:300,difficulty:'medio',emoji:'🔄',
   grad:'linear-gradient(270deg,#001a20,#001015,#001a20)',anim:'circuit',video:'',
   desc:'5 ejercicios funcionales encadenados que mejoran fuerza, coordinación y resistencia simultáneamente.',
   steps:['1 min: Sentadilla + press de hombros (isométrico)','1 min: Estocada + rotación de torso','1 min: Plancha + elevación de brazo (bird dog)','1 min: Puente + abdominales','1 min: Vuelta a la calma']},
  {id:'equilibrio_fuerza',name:'Equilibrio y Fuerza',duration:300,difficulty:'medio',emoji:'⚖️',
   grad:'linear-gradient(270deg,#0a001a,#060014,#0a001a)',anim:'stretch',video:'',
   desc:'Combina ejercicios de equilibrio con trabajo de fuerza para activar los músculos estabilizadores profundos.',
   steps:['1 min: Sentadilla en un pie (asistida)','1 min: Guerrero 3 (yoga, 30s c/lado)','1 min: Plancha unilateral','1 min: Puente con elevación de pierna','1 min: Estiramiento final']},
  {id:'cardio_fuerza',name:'Cardio y Fuerza',duration:300,difficulty:'medio',emoji:'⚡',
   grad:'linear-gradient(270deg,#002015,#001810,#002015)',anim:'circuit',video:'',
   desc:'Intervalos que alternan ejercicios de fuerza con movimientos cardiovasculares para máximo beneficio.',
   steps:['1 min: Sentadillas (fuerza)','1 min: Jumping jacks (cardio)','1 min: Flexiones (fuerza)','1 min: Marcha rápida con rodillas altas (cardio)','1 min: Plancha y respiración (estabilidad)']},
  // ── DIFÍCIL 1min ──
  {id:'burpees',name:'Burpees Express',duration:60,difficulty:'dificil',emoji:'🔥',
   grad:'linear-gradient(270deg,#200010,#100020,#200010)',anim:'squat',video:'',
   desc:'El ejercicio total en su versión más intensa. 60 segundos de burpees para máxima quema calórica.',
   steps:['Parate con pies juntos','Bajá las manos al suelo, salto a plancha','Realizá una flexión (opcional)','Saltá de regreso y luego arriba con brazos']},
  {id:'saltos',name:'Saltos de Potencia',duration:60,difficulty:'dificil',emoji:'⬆',
   grad:'linear-gradient(270deg,#1a0020,#200010,#1a0020)',anim:'squat',video:'',
   desc:'Ejercicio pliométrico de máxima intensidad. Desarrolla potencia explosiva en piernas y glúteos.',
   steps:['Posición de sentadilla a la mitad','Cargá los brazos hacia abajo','Saltá explosivo hacia arriba','Aterrizá suavemente, repetí sin parar']},
  {id:'flexiones',name:'Flexiones Intensas',duration:60,difficulty:'dificil',emoji:'💪',
   grad:'linear-gradient(270deg,#200000,#100010,#200000)',anim:'plank',video:'',
   desc:'Máximas flexiones en 60 segundos. Pondrán a prueba tus pectorales, hombros y tríceps.',
   steps:['Posición de plancha, manos a ancho de hombros','Bajá el pecho al suelo (codos 45°)','Subí explosivo extendiendo brazos','Variante: rodillas en el suelo si necesario']},
  {id:'montanero',name:'Escalador',duration:60,difficulty:'dificil',emoji:'🧗',
   grad:'linear-gradient(270deg,#100020,#001020,#100020)',anim:'plank',video:'',
   desc:'Mountain climber: combiná cardio y fuerza en el ejercicio más completo que podés hacer en el suelo.',
   steps:['Posición de plancha alta (brazos extendidos)','Llevá la rodilla derecha al pecho rápido','Alternás con rodilla izquierda al pecho','Mantenés velocidad máxima 60 segundos']},
  {id:'squat_jump',name:'Squat Jumps',duration:60,difficulty:'dificil',emoji:'💥',
   grad:'linear-gradient(270deg,#200a00,#180600,#200a00)',anim:'squat',video:'',
   desc:'Sentadillas explosivas con salto para desarrollar potencia máxima en piernas y glúteos.',
   steps:['Bajá a sentadilla completa','Cargá la energía abajo','Saltá explosivo extendiendo todo el cuerpo','Aterrizá suave en sentadilla, repetí sin pausa']},
  {id:'pushup_explosivo',name:'Push-Up Explosivo',duration:60,difficulty:'dificil',emoji:'💪',
   grad:'linear-gradient(270deg,#200000,#150000,#200000)',anim:'plank',video:'',
   desc:'Flexiones pliométricas donde las manos despegan del suelo. Máxima potencia de empuje en 60 segundos.',
   steps:['Posición de plancha alta','Bajá rápido hasta el suelo','Empujá explosivo para que las manos despeguen','Aterrizá suave, absorbé el impacto, repetí']},
  {id:'plancha_rotacion',name:'Plancha con Rotación',duration:60,difficulty:'dificil',emoji:'🔄',
   grad:'linear-gradient(270deg,#100020,#0a0018,#100020)',anim:'plank',video:'',
   desc:'Plancha dinámica con rotación lateral que trabaja el core, oblicuos y hombros simultáneamente.',
   steps:['Posición de plancha alta','Rotá abriendo un brazo al cielo (plancha lateral)','Volvé al centro','Alternás lados con velocidad creciente']},
  {id:'sprint_lugar',name:'Sprint en el Lugar',duration:60,difficulty:'dificil',emoji:'🏃',
   grad:'linear-gradient(270deg,#1a1000,#140c00,#1a1000)',anim:'circuit',video:'',
   desc:'Sprint máximo corriendo en el lugar. Esfuerzo cardiovascular total en el menor espacio posible.',
   steps:['Comenzá con trote suave 10 seg','Aumentá la velocidad progresivamente','Los últimos 30 seg: velocidad máxima posible','Brazos activos, rodillas altas, talones atrás']},
  {id:'plyo_lunges',name:'Lunges Pliométricos',duration:60,difficulty:'dificil',emoji:'🦵',
   grad:'linear-gradient(270deg,#201000,#180c00,#201000)',anim:'squat',video:'',
   desc:'Estocadas con salto alternadas para desarrollar potencia explosiva y coordinación en piernas.',
   steps:['Bajá en estocada con rodilla derecha al frente','Saltá cambiando las piernas en el aire','Aterrizá en estocada con pierna izquierda','Mantené el ritmo explosivo sin pausas']},
  {id:'bear_crawl',name:'Bear Crawl',duration:60,difficulty:'dificil',emoji:'🐻',
   grad:'linear-gradient(270deg,#1a0010,#120008,#1a0010)',anim:'plank',video:'',
   desc:'El arrastre de oso trabaja todo el cuerpo a la vez: core, hombros, caderas y coordinación cruzada.',
   steps:['Cuadrupedia con rodillas a 2cm del suelo','Avanzá moviendo brazo y pierna contrarios','Mantené la espalda plana y el core activo','Si no tenés espacio, avanzá y retrocedé']},
  // ── DIFÍCIL 3min ──
  {id:'circuito_int',name:'Circuito Intenso',duration:180,difficulty:'dificil',emoji:'🔄',
   grad:'linear-gradient(270deg,#200010,#0a0020,#200010)',anim:'circuit',video:'',
   desc:'Circuito de alta intensidad que trabaja todo el cuerpo. Prepárate para sudar en 3 minutos.',
   steps:['45 seg: Burpees','45 seg: Saltos de potencia','45 seg: Flexiones rápidas','45 seg: Escaladores (mountain climbers)']},
  {id:'tabata',name:'Tabata Básico',duration:180,difficulty:'dificil',emoji:'⏱',
   grad:'linear-gradient(270deg,#1a0010,#100020,#1a0010)',anim:'circuit',video:'',
   desc:'Protocolo Tabata: 20 seg máxima intensidad, 10 seg descanso. El método de entrenamiento más efectivo.',
   steps:['20 seg al máximo: Sentadillas','10 seg: Descanso','20 seg al máximo: Flexiones','10 seg: Descanso — repetí el ciclo 3 veces']},
  {id:'core_fuego',name:'Core en Llamas',duration:180,difficulty:'dificil',emoji:'🔥',
   grad:'linear-gradient(270deg,#200000,#1a0010,#200000)',anim:'plank',video:'',
   desc:'Rutina de abdominales de alta intensidad. Tu core nunca más va a ser el mismo.',
   steps:['45 seg: Abdominales explosivos','45 seg: Elevaciones de piernas','45 seg: Planchas con rodilla al codo','45 seg: Bicicleta abdominal rápida']},
  {id:'hiit_piernas',name:'HIIT de Piernas',duration:180,difficulty:'dificil',emoji:'🦵',
   grad:'linear-gradient(270deg,#200800,#180600,#200800)',anim:'squat',video:'',
   desc:'Protocolo HIIT exclusivo de piernas: el grupo muscular más grande, la quema calórica más alta.',
   steps:['45 seg: Squat jumps','45 seg: Lunges pliométricos','45 seg: Sentadilla isométrica (aguantá)','45 seg: Sprint en el lugar']},
  {id:'upper_explosivo',name:'Upper Body Explosivo',duration:180,difficulty:'dificil',emoji:'💪',
   grad:'linear-gradient(270deg,#200010,#180008,#200010)',anim:'plank',video:'',
   desc:'Circuito de alta intensidad para tren superior: pectorales, hombros, tríceps y core.',
   steps:['45 seg: Push-up explosivo','45 seg: Tríceps dips en silla','45 seg: Plancha con toque de hombros','45 seg: Superman pulsado']},
  {id:'pliometrico',name:'Circuito Pliométrico',duration:180,difficulty:'dificil',emoji:'💥',
   grad:'linear-gradient(270deg,#1a0020,#120018,#1a0020)',anim:'circuit',video:'',
   desc:'Entrenamiento pliométrico puro para desarrollar potencia explosiva en todo el cuerpo.',
   steps:['45 seg: Squat jumps','45 seg: Push-up explosivo','45 seg: Lunges pliométricos','45 seg: Burpees sin flexión']},
  {id:'core_explosivo',name:'Core Explosivo',duration:180,difficulty:'dificil',emoji:'🔥',
   grad:'linear-gradient(270deg,#200000,#180000,#200000)',anim:'plank',video:'',
   desc:'Core de alta intensidad con movimientos explosivos para construir un centro fuerte y potente.',
   steps:['45 seg: Abdominales explosivos (V-ups)','45 seg: Escaladores máximos','45 seg: Plancha con salto de pies','45 seg: Tijeras de piernas rápidas']},
  {id:'tabata_piernas',name:'Tabata de Piernas',duration:180,difficulty:'dificil',emoji:'⏱',
   grad:'linear-gradient(270deg,#1a1000,#120c00,#1a1000)',anim:'circuit',video:'',
   desc:'Protocolo Tabata aplicado a piernas: 6 rondas de 20 seg máximo + 10 seg descanso.',
   steps:['20 seg: Squat jumps / 10 seg: descanso','20 seg: Lunges pliométricos / 10 seg: descanso','20 seg: Sentadilla isométrica / 10 seg: descanso','Repetí el ciclo 2 veces']},
  {id:'full_intenso',name:'Full Body Intenso',duration:180,difficulty:'dificil',emoji:'🏋',
   grad:'linear-gradient(270deg,#0a2000,#061800,#0a2000)',anim:'circuit',video:'',
   desc:'Circuito de alta intensidad de cuerpo completo sin descanso. El minuto más difícil se vuelve el más orgulloso.',
   steps:['45 seg: Burpees','45 seg: Push-up explosivo','45 seg: Squat jumps','45 seg: Escaladores']},
  {id:'resistencia_max',name:'Resistencia Máxima',duration:180,difficulty:'dificil',emoji:'⚡',
   grad:'linear-gradient(270deg,#001a20,#001018,#001a20)',anim:'circuit',video:'',
   desc:'Circuito diseñado para llevar la resistencia muscular y cardiovascular al límite en 3 minutos.',
   steps:['1 min: Sentadillas sin parar (ritmo constante)','1 min: Flexiones sin parar (las que puedas)','1 min: Plancha sin bajar (si podés)']},
  // ── DIFÍCIL 5min ──
  {id:'fuerza_maxima',name:'Fuerza Máxima',duration:300,difficulty:'dificil',emoji:'🏆',
   grad:'linear-gradient(270deg,#200500,#180400,#200500)',anim:'plank',video:'',
   desc:'Protocolo de fuerza máxima con poco descanso. Cada serie al límite para estímulo muscular profundo.',
   steps:['1 min: Max push-ups (descansá lo mínimo)','1 min: Max sentadillas','1 min: Max abdominales','1 min: Max burpees','1 min: Plancha de cierre']},
  {id:'cardio_extremo',name:'Cardio HIIT Extremo',duration:300,difficulty:'dificil',emoji:'🔥',
   grad:'linear-gradient(270deg,#201000,#180c00,#201000)',anim:'circuit',video:'',
   desc:'El protocolo cardiovascular más intenso de RETOFIT. Equivale a 40 minutos de cardio moderado.',
   steps:['1 min: Burpees a máxima velocidad','1 min: Sprint en el lugar','1 min: Squat jumps','1 min: Escaladores máximos','1 min: Jumping jacks de cierre']},
  {id:'resistencia_total',name:'Resistencia Total',duration:300,difficulty:'dificil',emoji:'⚡',
   grad:'linear-gradient(270deg,#1a0020,#120018,#1a0020)',anim:'circuit',video:'',
   desc:'Circuito de resistencia completa: cardiovascular, muscular y mental. El reto más completo.',
   steps:['1 min: Circuito superior (push-up + tríceps)','1 min: Circuito inferior (sentadilla + estocada)','1 min: Core (plancha + abdominales)','1 min: Full body (burpees)','1 min: Vuelta a la calma activa']},
  {id:'funcional_avanzado',name:'Funcional Avanzado',duration:300,difficulty:'dificil',emoji:'🔄',
   grad:'linear-gradient(270deg,#002010,#001a0c,#002010)',anim:'circuit',video:'',
   desc:'Movimientos funcionales avanzados que trabajan fuerza, potencia y coordinación integradas.',
   steps:['1 min: Turkish get-up (con peso imaginario)','1 min: Sentadilla + salto + plancha','1 min: Escaladores con rotación','1 min: Bear crawl + push-up','1 min: Respiración y estiramiento']},
  {id:'quema_total',name:'Quema Total',duration:300,difficulty:'dificil',emoji:'💥',
   grad:'linear-gradient(270deg,#200a00,#180800,#200a00)',anim:'circuit',video:'',
   desc:'5 minutos diseñados para la máxima quema calórica post-ejercicio (efecto EPOC). Sin piedad.',
   steps:['1 min: Squat jumps','1 min: Push-up explosivo','1 min: Lunges pliométricos','1 min: Escaladores','1 min: Sprint en el lugar']},
  {id:'potencia',name:'Protocolo de Potencia',duration:300,difficulty:'dificil',emoji:'⚡',
   grad:'linear-gradient(270deg,#1a0010,#120008,#1a0010)',anim:'squat',video:'',
   desc:'Entrenamiento de potencia explosiva: cada movimiento al máximo, cada repetición cuenta.',
   steps:['1 min: Saltos de cajón imaginario (máxima altura)','1 min: Push-up con aplauso (o explosivo)','1 min: Pistol squat asistido','1 min: Bear crawl explosivo','1 min: Respiración de recuperación']},
  {id:'fulcuerpo',name:'Rutina Full Cuerpo',duration:300,difficulty:'dificil',emoji:'🏋',
   grad:'linear-gradient(270deg,#0a2000,#002010,#0a1000)',anim:'circuit',video:'',
   desc:'Circuito de 5 minutos: plancha, sentadillas, flexiones y estiramiento. La mejor inversión de tu día.',
   steps:['1 min: Plancha de poder','1 min: Sentadillas rápidas','1 min: Flexiones (modificadas ok)','1 min: Saltos suaves','1 min: Estiramiento final']},
  {id:'hiit_full',name:'HIIT Completo',duration:300,difficulty:'dificil',emoji:'⚡',
   grad:'linear-gradient(270deg,#1a0020,#002010,#1a0020)',anim:'circuit',video:'',
   desc:'El protocolo de alta intensidad completo. 5 minutos que equivalen a 30 minutos de cardio moderado.',
   steps:['1 min: Burpees (ritmo moderado)','1 min: Saltos de potencia','1 min: Escaladores','1 min: Sentadillas jump','1 min: Plancha abdominal final']},
  {id:'atleta',name:'Rutina del Atleta',duration:300,difficulty:'dificil',emoji:'🏅',
   grad:'linear-gradient(270deg,#001a20,#001018,#001a20)',anim:'circuit',video:'',
   desc:'Entrenamiento de atleta amateur: combina velocidad, fuerza y resistencia en un bloque de 5 minutos.',
   steps:['1 min: Sprint en el lugar + rodillas altas','1 min: Push-up + escalador (10+10)','1 min: Squat jump + estocada','1 min: Bear crawl + plancha','1 min: Respiración de atleta (recuperación activa)']},
  {id:'guerrero',name:'Rutina del Guerrero',duration:300,difficulty:'dificil',emoji:'⚔',
   grad:'linear-gradient(270deg,#200000,#100020,#200000)',anim:'circuit',video:'',
   desc:'El desafío máximo de RETOFIT. 5 minutos de intensidad pura que transforman tu día y tu cuerpo.',
   steps:['1 min: Calentamiento intenso','1 min: Tabata de sentadillas','1 min: Tabata de flexiones','1 min: Escaladores máximos','1 min: Enfriamiento y respiración']}
];

// ─── TIPS POOL ────────────────────────────────────────────────────────────────
const TIPS = [
  "Ajustá tu silla para que las rodillas formen 90°. Tu columna te lo agradecerá.",
  "Cada 30 minutos, parate y caminá 2 minutos. Rompé el sedentarismo.",
  "Revisá tu postura ahora: hombros atrás, mentón paralelo al suelo, pies planos.",
  "El monitor debería estar a nivel de tus ojos para evitar dolor de cuello.",
  "Si trabajás con laptop, usá un soporte elevador para no agachar la cabeza.",
  "Tomá un vaso de agua antes de cada reto. Mejora el rendimiento hasta un 20%.",
  "Si tenés sed, ya estás deshidratado. Bebé agua de manera preventiva.",
  "El café deshidrata. Por cada taza, tomá un vaso de agua extra.",
  "Empezá el día con 500ml de agua antes del desayuno. Activa el metabolismo.",
  "Poné una botella de agua en tu escritorio como recordatorio visual.",
  "La respiración profunda activa el sistema nervioso parasimpático y reduce el cortisol.",
  "Inhalá 4 seg, aguantá 4, exhalá 8. Repetilo 4 veces cuando estés estresado.",
  "Respirar por la nariz filtra el aire y mejora la oxigenación cerebral.",
  "La técnica 4-7-8: inhalar 4s, retener 7s, exhalar 8s. Ideal antes de dormir.",
  "Respirá desde el abdomen, no el pecho. Tu diafragma es el músculo principal.",
  "Un minuto de movimiento cada hora reduce el riesgo cardiovascular un 33%.",
  "Las escaleras queman 4 veces más calorías que el ascensor.",
  "Hacé sentadillas mientras esperás que hierva el agua.",
  "Estirá los brazos hacia arriba al despertar. Activa más de 200 músculos.",
  "Caminá mientras hablás por teléfono. Fácil y efectivo.",
  "El músculo crece durante el descanso, no durante el ejercicio.",
  "Dormir menos de 6 horas reduce la eficiencia del ejercicio a la mitad.",
  "Un baño frío post-ejercicio reduce la inflamación y acelera la recuperación.",
  "Estirar después de ejercitarte aumenta la flexibilidad un 30% más que hacerlo antes.",
  "Escuchá tu cuerpo: el dolor agudo es señal de parar, el ardor muscular es progreso.",
  "Las proteínas dentro de 30 min post-ejercicio maximizan la recuperación muscular.",
  "5 porciones de frutas y verduras diarias mejoran el rendimiento físico.",
  "Los carbohidratos complejos son el combustible para ejercicios de más de 3 minutos.",
  "Evitá ejercitarte con el estómago lleno. Esperá al menos 90 minutos.",
  "El plátano es el snack perfecto pre-ejercicio: potasio + glucosa de rápida absorción.",
  "El ejercicio regular aumenta el volumen del hipocampo, mejorando la memoria.",
  "5 minutos de movimiento reducen la ansiedad mejor que 5 minutos de redes sociales.",
  "Celebrá cada reto completado. Tu cerebro refuerza el hábito con dopamina.",
  "Visualizarte haciendo el ejercicio mejora el rendimiento hasta un 15%.",
  "La música a 120-140 BPM sincroniza tu ritmo cardíaco y mejora la resistencia.",
  "Los hábitos se forman con consistencia, no intensidad. 1 min diario vale más que 1h semanal.",
  "Hacé el reto a la misma hora cada día. Tu cuerpo lo anticipará y pedirá movimiento.",
  "Vinculá el ejercicio a algo que ya hacés: después del café, antes de almorzar.",
  "El 80% del éxito fitness es simplemente presentarte. Empezar es lo más difícil.",
  "Trackeá tu progreso. Ver los números crecer es el mejor motivador.",
  "Si trabajás en oficina: cada vez que recibís un mail, hacé 5 sentadillas.",
  "Un escritorio de pie reduce el dolor de espalda un 54% en personas sedentarias.",
  "Los microdescansos de 90 seg cada 25 min triplican la productividad.",
  "Hablar con un colega en persona (en vez de chatear) suma pasos sin notarlo.",
  "Estirá la muñeca y los dedos cada 20 minutos si escribís mucho en computadora.",
  "La luz solar en la mañana regula el cortisol y mejora tu energía durante el día.",
  "Salir descalzo al pasto 10 minutos reduce el cortisol. Se llama 'grounding'.",
  "Reír 15 minutos al día quema hasta 40 calorías y libera endorfinas.",
  "El frío activa la grasa parda y acelera el metabolismo. Una ducha fría de 30s ya suma.",
  "Mantener una postura de poder por 2 minutos antes de un desafío baja el cortisol."
];
